//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lufthavn
{
    using System;
    using System.Collections.Generic;
    
    public partial class Route
    {
        public string Departure { get; set; }
        public string Arrival { get; set; }
        public string ICAO { get; set; }
    
        public virtual Airline Airline { get; set; }
        public virtual Airport AirportArrival { get; set; }
        public virtual Airport AirportDeparture { get; set; }
    }
}
